services:
  - type: web
    name: query-gen-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: DB_NAME
        value: neondb
      - key: DB_USER
        value: neondb_owner
      - key: DB_PASSWORD
        value: your_db_password
      - key: DB_HOST
        value: your_db_host
      - key: DB_SSLMODE
        value: require
      - key: GOOGLE_API_KEY
        value: your_gemini_api_key
